# Metadata for the Smart-Plugins
plugin:
# Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Implementiert LevelJET Regenwasser Fuellstandsanzeige (www.projet.de)'
        en: 'Plugin implements LevelJET water level indicator (www.projet.de)'
    maintainer: 'knatter'
#    tester:                        # Who tests this plugin?
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py
    version: 1.0.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    classname: LevelJet                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    serialport:
        type: str
        mandatory: TRUE
        description:
            de: 'Pfad zu serieller USB Schnittstelle (default: /dev/ttyUSB1)'
            en: 'Path to serail USB interface (optional, default: /dev/ttyUSB1)'
            
    update_cycle:
        type: str
        mandatory: False
        description:
            de: 'zyklische Abfrage [sek.) (default: 240)'
            en: 'cyclic update request [sec.] (default: 240)'
            
    baudrate:
        type: str
        mandatory: False
        description:
            de: 'Baudrate (default: 19200)'
            en: 'Baudrate (default: 19200)' 

item_attributes:
    # Definition of item attributes defined by this plugin
    ljet_cmd:
        type: str
        valid_list:
        - dist
        - level
        - liter
        - percent
        - outflags
