# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ermöglicht die Verwendung von Kalendern (ICS)'
        en: 'Allows using of calendars (ICS)'
    description_long:
        de: 'Ermöglicht die Verwendung von Kalendern (ICS)\n
            Es können sowohl Dateien als auch Onlinefeeds eingebunden werden.
            '
        en: 'Allows using of calendars (ICS)\n
            You can use offline files and online feeds.
            '
    maintainer: cmalo (mknx)
    tester: ohinckel, onkelandy
    keywords: calendar ical ics

    version: 1.3.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: iCal                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    cycle:
        type: int
        default: 3600
        description:
            de: "Definiert in Sekunden das Intervall, in dem der Kalender aktualisert werden soll."
            en: "Specifies the interval in seconds to update the calendars."

    calendars:
        type: list(str)
        description:
            de: "Liste von Kalendern die automatisch aktualisiert und via `sh.ical()` Funktion abgerufen werden kann."
            en: "list of calendars to automatically keep up to date and provided via `sh.ical()` function."
        description_long:
            de: "Liste von Kalendern die automatisch aktualisiert und via `sh.ical()` Funktion abgerufen werden kann. Konfiguriert optional einen Alias und die URI des Kalenders, die sowohl auf ein lokales File als auch einen Onlinefeed mit `http://` verweisen kann.\n
            Beispiel: holidays:http://cal.server/holidays.ical"
            en: "list of calendars to automatically keep up to date and provided via `sh.ical()` function. Configures an alias (optional) and the URI of calendar, which can be a local file or a remote file when starting with `http://`.\n
            Example: holidays:http://cal.server/holidays.ical"

item_attributes:
    # Definition of item attributes defined by this plugin
    ical_calendar:
        type: str
        description:
            de: "Dieses Attribut konfiguriert eine Verbindung zwischen Item und entsprechendem Kalender."
            en: "This configures a connection between the item and the given calendar."
        description_long:
            de: "Dieses Attribut konfiguriert eine Verbindung zwischen Item und entsprechendem Kalender, der entweder als URI oder als Kalender Alias (im etc/plugin.yaml definiert) angegeben wird. Der konfigurierte Kalender wird automatisch zum internen Kalender-Zwischenspeicher hinzugefügt und aktualisiert.\n
            \n
            Das Item wird auf Wahr gesetzt, sobald ein Event im Moment stattfindet. Ansonsten ist es falsch.\n
            \n
            Das Aktualisierungsintervall ist derzeit auf eine Minute festgelegt. Das beduetet, jede Minute wird der Kalender auf Events geprüft und das Item bei Bedarf aud Wahr geschaltet.
            "
            en: "This configures a connection between the item and the given calendar. You can specify the calendar URI or the calendar alias (as defined in the etc/plugin.yaml). The configured calendar will automatically be added to the internal calendar cache and will automatically be updated.\n
            \n
            When configured, each time an event is taken place at the moment, the item will be set to true or if not, to false.\n
            \n
            The update interval for the item updates is currently at one minute, which means each minute it will be checked if an event is taking place and
            the items will be updated."

plugin_functions:
    # Definition of function interface of the plugin
    ical:
        type: dict
        description:
            de: "Es wird ein dictionary mit einem datetime.date Objekt als Key und verschiedenen Detailwerten zurückgeliefert."
            en: "It returns a dictonary with a datetime.date object as key and an array with different detail values."
        description_long:
            de: "Es wird ein dictionary mit einem datetime.date Objekt als Key und folgenden Arraywerten zurückgeliefert:\n
            die Event Startzeit, die Event Endzeit, die Eventkategorie (z.B. privat), die Eventzusammenfassung (z.B. die Notizen)\n
            \n
            Wenn ein Kalender öfters verwendet werden soll, wird empfohlen, diesen in der etc/plugin.yaml zu konfigurieren.
            "
            en: "It returns a dictonary with a datetime.date object as key and an array including\n
            the event start time, the event end time, the event's class type (e.g. private calendar entry), the event's summary, i.e. content\n
            \n
            If you want to use a calendar more regularly it could be helpful to configure this calendar in the plugin configuration.
            "
        parameters:
            ics:
                type: str
                default: None
                description:
                    de: 'eine lokale Datei, eine mit http://  startende URL oder ein Kalender-Alias aus der Pluginkonfiguration'
                    en: 'specify a local file, a url starting with http:// or a calendar alias configured in the plugin configuration.'

            delta:
                type: int
                default: 1
                description:
                    de: 'wieviele zusätzliche Tage analysiert werden sollen.'
                    en: 'how many additional days should the analysed.'

            offset:
                type: int
                default: 0
                description:
                    de: 'wann der zu analysierende Zeitrahmen starten soll.'
                    en: 'when should the analysed timeframe start.'

            prio:
                type: int
                default: 1
                description:
                    de: 'Falls in einem Kalendereintrag Felder mehrfach vorkommen, kann hier bestimmt werden, das wievielte Feld priorisiert werden soll.'
                    en: 'If in one calendar entry a field is present multiple times you can define which occurence should be prioritized.'

            verify:
                type: bool
                default: True
                description:
                    de: 'Bestimmt, ob eine https URL per SSL verifiziert werden soll oder nicht.'
                    en: 'Defines if a https URL should be verified via SSL or not.'
