sudo: false
language: python

matrix:
    include:
      - python: 3.5
      - python: 3.6
      - python: 3.7
        dist: xenial

env:
    - REPOSITORY_ORIGIN=plugins

before_install:
    - sudo apt-get install libudev-dev
    - sudo apt-get install librrd-dev libpython3-dev
install:
    - pip install tox-travis virtualenv

script:
    - sh .travis.sh
