# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Integration von Wetter.COM'
        en: 'Integrating Wetter.COM'
    maintainer: '? (Jan N. Klug)'
    tester: psilo909, onkelandy
    keywords: weather
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.4.0                 # Plugin version
    sh_minversion: 1.4             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: wettercom           # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    project:
        type: str
        default: ''
        mandatory: True
        description:
            de: 'Projektname für die wetter.com API'
            en: 'Project name for the wetter.com API'

    apikey:
        type: str
        default: ''
        mandatory: True
        description:
            de: 'Key für die wetter.com API'
            en: 'key for the wetter.com API'

item_attributes:
    # Definition of item attributes defined by this plugin
