# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Prowl Unterstützung'
        en: ''
    maintainer: Foxi352 (mknx)
#    tester:                        # Who tests this plugin?
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.3.0                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: Prowl               # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

#    instance:
#        type: str
#        default: ''
#        description:
#            de: 'Eindeutiger Identifier für die Instanz des Plugins. Kann bei nur einer konfigurierten Instanz des Plugins entfallen.'
#            en: 'Unique identifier for each instance of the plugin. Can be omitted if only one device instance of the plugin is configured.'


item_attributes:
    # Definition of item attributes defined by this plugin
    
