# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Implementierung seperater Logs'
        en: ''
    maintainer: '? (JanT112)'
    tester: Sandman60, onkelandy
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.3.0                 # Plugin version
    sh_minversion: 1.4c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: OperationLog        # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    name:
        type: str
        description:
            de: 'Definiert den Namen des Logs'
            en: 'Defines the name of the log'
    maxlen:
        type: int
        default: 50
        description:
            de: 'Gibt an, wieviele Einträge im Speicher vorgehalten werden'
            en: 'Specifies how many log entries will be kept in memory'
    cache:
        type: bool
        default: True
        description:
            de: 'Aktiviert die Caching-Funktion für das Log (Log bleibt bei Neustart erhalten)'
            en: 'Activates the caching for the log (log will be restored on restarts)'
    logtofile:
        type: bool
        default: True
        description:
            de: 'Aktiviert das Schreiben des Logs in eine Datei'
            en: 'Activates logging to file'
    filepattern:
        type: str
        default: '{year:04}-{month:02}-{day:02}-{name}.log'
        description:
            de: 'Definiert das Namensformat für die Logdateien'
            en: 'Defines the name patter for the log files'
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
