# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Anbindung an das Viessmann Backend an SmartHomeNG'
        en: 'Plugin to connect the Viessmann backend with SmartHomeNG'
    maintainer: aschwith 
    tester: 'n/a'
    state: develop
    keywords: Viessmann, ViCare, Vitocontrol
    #documentation: 
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1916122-support-thread-f%C3%BCr-das-viessmann-plugin

    version: 1.9.0                  # Plugin version
    sh_minversion: 1.9.0            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: True
    classname: Vicare               # class containing the plugin

parameters:

    clientID:
        type: str
        mandatory: True
        description:
            de: "Client ID (via Viessmann Developper API Portal generiert)"
            en: "Client id (generated via Viessmann developper api portal)"

    redirectUrl:
        type: str
        mandatory: True
        description:
            de: "Redirect Url (via Viessmann Developper API Portal angelegt)"
            en: "Redirect uri (defined via Viessmann Developper API Portal)"

    accessToken:
        type: str
        gui_type: readonly 
        description:
            de: "Token (beim Oauth2 Verfahren generiert)"
            en: "Token (generated during the Oauth2 procedure)"

    refreshToken:
        type: str
        gui_type: readonly 
        description:
            de: "Refresh token (beim Oauth2 Verfahren generiert)"
            en: "Refresh token (generated during the Oauth2 procedure)"

    

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    vicare_tx_key:
        type: str
        description:
            de: 'Key für das Senden von Kommandos an das Viessmann Backend'
            en: 'Key for sending commands to the Viessmann backend'
        valid_list:
        - 'heating.circuits.1.operating.programs.normal'
        - 'heating.circuits.1.operating.programs.reduced'
        - 'heating.dhw.temperature.main'
        - 'heating.dhw.operating.modes.active'
        - 'heating.circuits.1.operating.modes.active'

    vicare_tx_path:
        type: list
        description:
            de: 'Array mit Einträgen zum Pfad des Sendekommandos im Feature command'
            en: 'Array of entries to find command in json response'

    vicare_rx_key:
        type: str
        description:
            de: 'Key für den Empfang von Statusinformationen aus dem Viessmann Backend'
            en: 'Key for receiving status informations from the Viessmann backend'
        valid_list:
        - 'boilerSerial'
        - 'heating.circuits.1.sensors.temperature.supply'
        - 'heating.circuits.1.operating.programs.active'
        - 'heating.circuits.1.operating.modes.heating'
        - 'heating.circuits.1.operating.modes.active'
        - 'heating.gas.consumption.total'
        - 'heating.circuits.1.operating.programs.comfort'
        - 'heating.circuits.1.operating.programs.normal'
        - 'heating.circuits.1.operating.programs.reduced'
        - 'heating.circuits.1.circulation.pump'
        - 'heating.operating.programs.holiday'
        - 'heating.dhw'
        - 'heating.dhw.temperature.main'
        - 'heating.dhw.oneTimeCharge'
        - 'heating.dhw.operating.modes.active'
        - 'heating.dhw.sensors.temperature.dhwCylinder'
        - 'heating.dhw.sensors.temperature.hotWaterStorage'
        - 'heating.boiler.sensors.temperature.commonSupply'
        - 'heating.boiler.temperature'
        - 'heating.sensors.temperature.outside'
        - 'heating.power.consumption.summary.heating'
        - 'heating.power.consumption.total'
        - 'device.messages.errors.raw'

    vicare_path:
        type: list
        description:
            de: 'Array mit Pfad zur Eigenschaft in Feature property'
            en: 'Array of entries to find property in json response'


plugin_functions: NONE 

logic_parameters: NONE

item_structs: NONE





