# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface               # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'jq json parser plugin'
        en: 'jq json parser plugin'
    maintainer: t3r
    tester: none (yet)
    keywords: solar power
    documentation: http://smarthomeng.de/user/plugins_doc/config/not-yet.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/not-yet

    version: 0.0.1                 # Plugin version
    sh_minversion: 1.4             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True          # plugin supports multi instance
    classname: SHJQ             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    url:
        type: str
        mandatory: True
        description:
            de: 'URL of the json input (e.g. http://foo.bar/input.json or file:///path/to/data.json)'
            en: 'URL of the json input (e.g. http://foo.bar/input.json or file:///path/to/data.json)'
    cycle:
        type: num
        mandatory: False
        description:
            de: 'The polling interval for the given url in seconds'
            en: 'The polling interval for the given url in seconds'


item_attributes:
    # Definition of item attributes defined by this plugin
    shjq_source:
        type: str
    
