# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: protocol                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Unterstützung des Extensible Messaging and Presence Protocol (XMPP). Unterstützt z.Zt. nur das Senden von Nachrichten'
        en: 'Support for the Extensible Messaging and Presence Protocol (XMPP). Currently only message sending supported'
    maintainer: '? (Skender Haxhimolla)'
    tester: ohinckel                   # Who tests this plugin?
#    keywords: kwd1 kwd2            # keywords, where applicable
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page

# Following entries are for Smart-Plugins:
    version: 1.3.3                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    classname: XMPP                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    jid:
        type: str
        mandatory: True
        description:
            de: 'Gibt den Benutzernamen / JID des zu nutzenden Accounts an'
            en: 'Specifies the username / JID of the account to use'
    password:
        type: str
        mandatory: True
        hide: True
        description:
            de: 'Gibt das Passwort für den zu nutzenden Account an'
            en: 'Specifies the password of the account to use'
    
item_attributes: NONE
    # Definition of item attributes defined by this plugin
    
