# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Dieses Plugin liefert die Gamma-Ortsdosisleistung (ODL) in µSv/h  von mehreren Stationen in Deutschland (zur Verfügung gestellt durch das Bundesamt für Strahlenschutz). Mehr Informationen unter https://odlinfo.bfs.de. Nutzungsbedingungen siehe https://www.imis.bfs.de/geoportal/resources/sitepolicy.html.'
        en: 'This plugin retrieves the Gamma-Ortsdosisleistung (ODL) in from several measuring stations (by "Bundesamt für Strahlenschutz") in Germany. For more information see https://odlinfo.bfs.de. For the terms of use see https://www.imis.bfs.de/geoportal/resources/sitepolicy.html.'
    maintainer: psilo909
    tester: Sandman60
    state: ready
    keywords: radioactivity
    documentation: https://smarthomeng.de/user/plugins_doc/config/odlinfo.html
    support: https://knx-user-forum.de/node/986480

    version: 1.5.0                 # Plugin version
    sh_minversion: 1.6             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: ODLInfo             # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml

item_attributes: NONE
    # Definition of item attributes defined by this plugin

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:

    get_stations:
        type: list(dict)
        description:
            de: "Gibt ein Array of DICTs mit allen verfügbaren Messstationen zurück. Keys eines DICTs:<br/><br/>
            id: Die internationale ID der Messstelle.<br/>
            kenn: Die Messstellenkennung, wie sie auch auf ODL-Info verwendet wird.<br/>
            plz: Die Postleitzahl der Messstelle.<br/>
            name: Der Name bzw. Ortsname der Messstelle.<br/>
            site_status: Der Status der Messstelle als Zahl. (1 = in Betrieb, 2 = Defekt, 3 = Testbetrieb)<br/>
            site_status_text: Der Status der Messstelle als Text.<br/>
            kid: ID des Messnetzknotens, dem die Messstelle zugeordnet ist. (1 = Freiburg, 2 = Berlin, 3 = München, 4 = Bonn, 5 = Salzgitter, 6 = Rendsburg)<br/>
            height_above_sea: Höhe der Messstelle über NN.<br/>
            start_measure: Startzeitpunkt der Messperiode für den gegebenen Messwert.<br/>
            end_measure: Endzeitpunkt der Messperiode für den gegebenen Messwert.<br/>
            value: Der Messwert.<br/>
            value_cosmic: Kosmischer Anteil des Messwertes.<br/>
            value_terrestrial: Terrestrischer Anteil des Messwertes.<br/>
            unit: Einheit zu dem Messwert.<br/>
            validated: Prüfstatus des Messwertes. (1 = geprüft, 2 = ungeprüft)<br/>
            nuclide: Bezeichnung der Messgröße.<br/>
            duration: Dauer der Messperiode."
            en: "Returns an Array of DICTs with all available measuring stations. Key of a DICT:<br/><br/>
            id: International ID of a measuring point.<br/>
            kenn: The masuring point identifier, as used in ODL-Info.<br/>
            plz: The postal code of the measuring point.<br/>
            name: The name / city name of the measuring point.<br/>
            site_status: The status of the measuring point as number. (1 = operating normally, 2 = malfunction, 3 = in test)<br/>
            site_status_text: The status of the measuring point as text.<br/>
            kid: ID of the measuring network node, the which the measuring point is associated. (1 = Freiburg, 2 = Berlin, 3 = München, 4 = Bonn, 5 = Salzgitter, 6 = Rendsburg)<br/>
            height_above_sea: Height above sea of the measuring point.<br/>
            start_measure: Start time of the measuring period of the given measuring value.<br/>
            end_measure: End time of the measuring period of the given measuring value.<br/>
            value: The measuring value.<br/>
            value_cosmic: Cosmic part of the measuring value.<br/>
            value_terrestrial: Terrestrial part of the measuring value.<br/>
            unit: Unit of the measuring value.<br/>
            validated: Check status of the measuring value. (1 = validated, 2 = unvalidated)<br/>
            nuclide: Name of the measurand.<br/>
            duration: Duration of the measurement period."

    get_station_for_id:
        type: dict
        description:
            de: "Gibt ein DICT mit Infos zur einer Messstation zurück. Keys: 'id', 'kenn', 'plz', 'name', 'site_status', 'site_status_text', 'kid', 'height_above_sea', 'start_measure', 'end_measure', 'value', 'value_cosmic', 'value_terrestrial', 'unit', 'validated', 'nuclide', 'duration'."
            en: "Returns a DICT with Infos of a measuring station. Keys: 'id', 'kenn', 'plz', 'name', 'site_status', 'site_status_text', 'kid', 'height_above_sea', 'start_measure', 'end_measure', 'value', 'value_cosmic', 'value_terrestrial', 'unit', 'validated', 'nuclide', 'duration'."

        parameters:
            odlinfo_id:
                type: str
                description:
                    de: "Array der IDs ('id' oder 'kenn') der Messstationen. Siehe Web-Interface des Plugins oder https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html."
                    en: "Array of IDs ('id' or 'kenn') of measuring stations. See web interface of plugin or https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html."

    get_stations_for_ids:
        type: list(dict)
        description:
            de: "Gibt ein Array von DICTs mit Infos zu Messstationen zurück. Keys: 'id', 'kenn', 'plz', 'name', 'site_status', 'site_status_text', 'kid', 'height_above_sea', 'start_measure', 'end_measure', 'value', 'value_cosmic', 'value_terrestrial', 'unit', 'validated', 'nuclide', 'duration'."
            en: "Returns an array of DICTs with Infos of measuring stations. Keys: 'id', 'kenn', 'plz', 'name', 'site_status', 'site_status_text', 'kid', 'height_above_sea', 'start_measure', 'end_measure', 'value', 'value_cosmic', 'value_terrestrial', 'unit', 'validated', 'nuclide', 'duration'."

        parameters:
            odlinfo_ids:
                type: list(str)
                description:
                    de: "Array der IDs ('id' oder 'kenn') der Messstationen. Siehe Web-Interface des Plugins oder https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html."
                    en: "Array of IDs ('id' or 'kenn') of measuring stations. See web interface of plugin or https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html."