# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Anbindung von einem Neato/Vorwerk Staubsauger Robotor an SmartHomeNG'
        en: 'Plugin to connect your Neato/Vorwerk Vacuum Robot with SmartHomeNG'
    maintainer: Thomas Hengsberg (thengsty)
    tester: aschwith
    state: develop                  # change to ready when done with development
    keywords: vorwerk, neato
    documentation: https://github.com/smarthomeng/plugins/blob/develop/neato/README.md
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1417295-support-thread-plugin-neato

    version: 1.6.3                  # Plugin version
    sh_minversion: 1.6              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: unknown
    classname: Neato         # class containing the plugin

parameters:
    account_email:
        type: str
        mandatory: True
        description:
            de: 'E-Mail Adresse des Neato/Vorwerk Accounts'
            en: 'E-Mail Adresse of your Neato/Vorwerk account'
    account_pass:
        type: str
        description:
            de: 'Kennwort des Neato/Vorwerk Accounts'
            en: 'Password of your Neato/Vorwerk account'
    robot_vendor:
        type: str
        mandatory: True
        default: 'neato'
        valid_list:
          - neato
          - vorwerk
        valid_list_description:
            de: ['Neato Roboter', 'Vorwerk Roboter']
            en: ['Neato robot', 'Vorwerk robot']
        description:
            de: 'Hersteller des Roboters'
            en: 'Vendor of your robot'
    token:
        type: str
        description:
            de: 'Oauth token fuer Vorwerk Login (basierend auf MyKobold Anmeldeverfahren)'
            en: 'Oauth token obtained for Vorwerk Login (based on MyKobold interface)'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    neato_name:
        type: str
        description:
            de: 'Name des Roboters'
            en: 'Name of the robot'
    neato_command:
        type: num
        description:
            en: 'Available Commands:
                61   start
                62   stop
                63   pause
                64   resume
                65   find me
                66   goToBase
                67   enableSchedule
                68   disableSchedule'
            de: 'Verfuegbare Kommandos:
                61   start
                62   stop
                63   pause
                64   fortsetzen
                65   finde mich
                66   fahre zur Basis
                67   Reinigungsplan aktivieren
                68   Reinigungsplan deaktivieren'
    neato_state:
        type: str
        description:
            en: 'Specifies the state of the Robot.
                0   Invalid
                1   Idle
                2   Busy
                3   Paused
                4   Error'
            de: 'Gibt den Zustand des Roboters an.
                0   Invalide
                1   Idle
                2   Beschaeftigt
                3   Pausiert
                4   Fehler'
    neato_alert:
        type: str
        description:
            en: 'Alert string if active'
            de: 'Alarmtext'

    neato_state_action:
        type: str
        description:
            en: 'If the state is busy, this element specifies what the robot is or has been busy doing.
            In the state is pause or error, it specifies the activity that the Robot was doing.
            If state is other, this element is null
                ========
                0	Invalid
                1	House Cleaning
                2	Spot Cleaning
                3	Manual Cleaning
                4	Docking
                5	User Menu Active
                6	Suspended Cleaning
                7	Updating
                8	Copying Logs
                9	Recovering Location
                10	IEC Test
                11	Map cleaning
                12	Exploring map (creating a persistent map)
                13	Acquiring Persistent Map IDs
                14	Creating & Uploading Map
                15	Suspended Exploration'
            de: 'Roboter Reinigungszustand'
    neato_isdocked:
        type: bool
        description:
            de: 'Roboter Docking Status'
            en: 'Robot docking status'
    neato_isscheduleenabled:
        type: bool
        description:
            de: 'Roboter Status Reinigunsplan'
            en: 'Robot cleaning schedule status'
    neato_ischarging:
        type: bool
        description:
            de: 'Roboter Ladestatus'
            en: 'Robot charging status'
    neato_chargepercentage:
        type: str
        description:
            de: 'Roboter Batteriestatus'
            en: 'Robot battery status'
    neato_message:
        type: str
        description:
            de: 'Roboter Nachricht'
            en: 'Robot message'
    neato_commandGoToBaseAvailable:
        type: bool
        description:
            de: 'Roboter Befehl zur Basis verfuegbar'
            en: 'Robot command return to base available'

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)
    #item_structs: NONE

plugin_functions:
    enable_schedule:
        type: void
        description:
            de: "Aktiviert den Reinigunsplan."
            en: "Activates cleaning schedule."
        parameters:
        # This function has no parameters
    disable_schedule:
        type: void
        description:
            de: "Deaktiviert den Reinigunsplan."
            en: "Disables cleaning schedule."
        parameters:
        # This function has no parameters

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
    #logic_parameters: NONE

