# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Wetterdaten über darksky.net.'
        en: 'Weather data via darksky.net.'
    maintainer: psilo909
    tester:
#    keywords: iot xyz
    documentation:
    support:
    keywords: weather
    version: 1.5.0.1              # Plugin version
    sh_minversion: 1.4c           # minimum shNG version to use this plugin
#    sh_maxversion:               # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True          # plugin supports multi instance
    classname: DarkSky            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    key:
        type: str
        mandatory: True
        description:
            de: 'Persönlicher API Key für darksky.net. Registrierung unter https://darksky.net/dev.'
            en: 'Your own personal API key for darksky.net. For your own key register to https://darksky.net/dev.'
    latitude:
        type: str
        mandatory: True
        description:
            de: 'Latitude des Ortes, für den die Wetterdaten abgerufen werden sollen.'
            en: 'Latitude for the location, of which weather data is requested.'
    longitude:
        type: str
        mandatory: True
        description:
            de: 'Longitude des Ortes, für den die Wetterdaten abgerufen werden sollen.'
            en: 'Longitude for the location, of which weather data is requested.'
    lang:
        type: str
        mandatory: False
        default: 'de'
        description:
            de: 'Sprache der zurückgelieferten Daten. Mögliche Werte siehe https://darksky.net/dev/docs.'
            en: 'Language of the data to be returned. Possible values see https://darksky.net/dev/docs.'
    units:
        type: str
        mandatory: False
        default: 'auto'
        description:
            de: 'Einheit der zurückgelieferten Daten. Mögliche Werte siehe https://darksky.net/dev/docs.'
            en: 'Unit of the returned data. Possible values see https://darksky.net/dev/docs.'
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
