# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung von iRobot Roomba Staubsaugern der Serie 900'
        en: ''
    maintainer: 'Zapfen83'
    tester: 
    keywords: irobot roomba             # keywords, where applicable
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

# Following entries are for Smart-Plugins:
    version: 1.0.0                 # Plugin version
    sh_minversion: 1.5             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    classname: ROOMBA_980              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

  adress:
    type: str
    default: True
    description:
      de: "IP Adresse des roomba Staubsaugers"
      en: ""

  blid:
    type: str
    default: True
    description:
      de: "Die blid des roomba Staubsaugers -> kann mit der getpassword.py ausgelesen werden"
      en: ""

  roombaPassword:
    type: str
    default: True
    description:
      de: "Das Passwort des roomba Staubsaugers -> kann mit der getpassword.py ausgelesen werden"
      en: ""

  cycle:
    type: num
    default: False
    description:
      de: "update des items alle x Sekunden, default wert 900"
      en: ""

item_attributes:
    # Definition of item attributes defined by this plugin

  status_batterie:
    type: num
    description:
      de: "Batterie ladewert in Prozent"
      en: ""

  status_bin_full:
    type: bool
    description:
      de: "Auffangbehälter voll"
      en: ""

  status_cleanMissionStatus_phase:
    type: str
    description:
      de: "Status was der Roomba gerade macht -> run / charge / ..."
      en: ""

  status_cleanMissionStatus_error:
    type: num
    description:
      de: "Fehlernummer"
      en: ""

  start:
    type: bool
    description:
      de: "Startet die Reinigung"
      en: ""

  stop:
    type: bool
    description:
      de: "Stoppt die Reinigung"
      en: ""

  dock:
    type: bool
    description:
      de: "Roomba fährt zur Homebase"
      en: ""

