# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Integration einer SQLite Datenbank - zu verwenden für smartVISU v2.8 und höher'
        en: 'Integration of a SQLite database - use this version of the plugin for smartVISU v2.8 and above'
    maintainer: '?'
#    tester:                        # Who tests this plugin?
    state: ready
    keywords: database
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.3.1                 # Plugin version
    sh_minversion: 1.3c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: SQL                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
#    cycle:
#        type: int
#        valid_min: 0
#        default: 300
#        description:
#            de: 'Zyklus-Zeit in dem die Datanbank Daten auf den Datenträger geschrieben werden'
#            en: 'cycle time for data beeing written to disc'

    path:
        type: str
        description:
            de: "Pfad zur Datenbank Datei (Pfad ohne Dateiname)"
            en: "Path to the database file (path without filename)"
        default: None*

    dumpfile:
        type: str
        description:
            de: "Falls dumpfile angegeben ist, erzeugt SmartHomeNG jede Nacht einen Datenbank Dump in diese Datei. (kompletter Pfad und Dateiname)"
            en: "If dumpfile is specified, SmartHomeNG dumps the database every night into this file. (Complete path and filename)"
        default: ''

item_attributes:
    # Definition of item attributes defined by this plugin
    sqlite:
        type: str
        description:
            de: "Falls auf 'yes' gesetzt, wird der Wert des Items in die sqlite Datenbank geschrieben."
            en: "If set to 'yes', the value of the item will be written to the sqlite database"
        valid_list: ['', 'yes', 'True', 'no', 'False']

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin

