# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Websocket Protokoll für Visus (smartVISU, etc.)'
        en: 'Support for a websocket protocol (for smartVISU, etc.)'
    maintainer: msinn
    tester: psilo909
#    keywords: iot xyz
    documentation: https://github.com/smarthomeNG/smarthome/wiki/Visu_Unterstuetzung        # url of documentation (wiki) page

    version: 1.1.3                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    ip:
        type: ipv4
        default: '0.0.0.0'
        description:
            de: ''
            en: ''
    
    port:
        type: int
        default: 2424
        valid_min: 0
        description:
            de: ''
            en: ''
    
    tls:
        type: bool
        default: False
        description:
            de: ''
            en: ''
    
    acl:
        type: str
        default: ro
        valid_list:
          - ro
          - rw
        description:
            de: ''
            en: ''
    
    wsproto:
        type: int
        default: 3
        valid_list:
          - 3
          - 4
        description:
            de: ''
            en: ''
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
