name: "SmartHomeNG Unittest Workflow"
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04 #latest
    steps:
     - name: Notidy Unit Tests
       run: |
         curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept:application/vnd.github.everest-preview+json" -H "Content-Type:application/json" https://api.github.com/repos/smarthomeNG/tests/dispatches --data "{'event_type':'build_application'}"
